braitenberg_target_controller:
  ros__parameters:
    vmax: 1.0
    wmax: 1.0
    kp: 0.15
    controller_type: 0
    ks: 1.0
    k_front: 1.6
    k_turn: 4.0
    k_tan: 10.0
    k_att: 1.2
    k_rep: 1.2
    k_v: 0.6
    d_dead: 0.6
    d_min: 0.08
    F_max: 0.2
    filter_beta: 0.85 

# controller_type: 0 --> ICC reactivo
# controller_type: 1 --> ICC geométrico

braitenberg_controller:
  ros__parameters:
    wheel_radius: 0.021
    wheel_base: 0.088
    v0: 0.1
    vmin: 0.0
    vmax: 0.2
    #wmax: 1.0
    max_detection_dist: 0.15
    max_range_default: 0.25
    control_hz: 20.0
    #max_accel_linear: 1e6
    #max_accel_angular: 1e6
    save_after_seconds: 60.0

    # Pesos: 8 valores cada uno (izquierda->derecha)
    GL: [0.0,0.0,0.0,0.0,-0.05,-0.075,-0.1,-0.00125]
    GR: [-0.00125,-0.1,-0.075,-0.05,0.0,0.0,0.0,0.0]

# controller_type: 0 --> ICC reactivo
# controller_type: 1 --> ICC geométrico